routes/admin.php
<?php


/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| This file is where the admin routes should be placed
| and remember all routes defined here are prefixed with /admin automatically
|
*/


Route::get('/', 'DashboardController@index')->name('dashboard');

Route::resource('stores', 'StoreController');
Route::resource('categories', 'CategoryController');
Route::post('categories/upload', 'CategoryController@upload');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

// pages
Route::get('about', 'HomeController@about');
Route::get('faq', 'HomeController@faq');
Route::get('contact', 'HomeController@getContact');
Route::post('contact', 'HomeController@postContact');
Route::get('terms', 'HomeController@terms');

app/Store.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Store extends Model
{
    protected $guarded = ['id'];

    use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function categories() {
        return $this->hasMany(Category::class);
    }

    public function scopeRanked($query) {
        return $query->orderBy('stores.rank', 'desc');
    }

    public function scopeTop($query) {
        return $query->where('stores.rank', '>', 0);
    }
}

app/Http/Controllers/Admin/StoreController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Store;

class StoreController extends Controller
{
    protected $store;

    public function __construct(Store $store)
    {
        $this->store = $store;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $stores = $this->store->ranked()->paginate(20);

        return admin_view('stores.index', [
            'stores' => $stores
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return admin_view('stores.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|min:5',
            'rank' => 'numeric',
        ]);

        $store = $this->store->create([
            'name' => $request->name,
            'rank' => $request->rank,
        ]);

        return back()->withSuccess('Store created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $store = $this->store->findOrFail($id);
        return admin_view('stores.edit', [
            'store' => $store
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $store = $this->store->findOrFail($id);

        $this->validate($request, [
            'name' => 'required|min:5',
            'rank' => 'numeric',
        ]);

        $store->update([
            'name' => $request->name,
            'rank' => $request->rank,
        ]);

        return back()->withSuccess('Store updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $store = $this->store->findOrFail($id);
        if($store->admin){
            session()->flash('error', 'Failed! You need to remove store\'s admin right first');
        }
        else{
            $store->delete();
            session()->flash('success', 'Store deleted successfully');
        }
        return response('reload');
    }
}

resources/views/admin/stores/create.blade.php
@extends('admin.layouts.app')

@section('title', 'New Store')

@section('content')
    <!-- start: page -->
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <section class="panel">
                <header class="panel-heading">
                    <h2 class="panel-title">New Store</h2>
                </header>
                <div class="panel-body">
                    <form class="form-horizontal form-bordered" role="form" method="POST" action="{{ admin_route('stores.store') }}">
                        {{ csrf_field() }}
                        <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-3 control-label" class="font-weight-normal">Name <span class="required">*</span></label>
                            <div class="col-md-6">
                                <input id="name" name="name" type="text" class="form-control" value="{{ old('name') }}" required>
                            </div>
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group {{ $errors->has('rank') ? ' has-error' : '' }}">
                            <label for="rank" class="col-md-3 control-label" class="font-weight-normal">Rank</label>
                            <div class="col-md-6">
                                <input id="rank" name="rank" type="number" class="form-control" value="{{ old('rank') }}" required>
                            </div>
                            @if ($errors->has('rank'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('rank') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="divider"> </div>
                        <div class="row">
                            <div class="col-sm-9 col-sm-offset-3">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
    <!-- end: page -->
@endsection

resources/views/admin/stores/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Edit Store')

@section('content')
    <!-- start: page -->
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <section class="panel">
                <header class="panel-heading">
                    <h2 class="panel-title">{{ $store->name }}</h2>
                </header>
                <div class="panel-body">
                    <form class="form-horizontal form-bordered" role="form" method="POST" action="{{ admin_route('stores.update', $store->id) }}>
                        {{ csrf_field() }}
                        {{ method_field('put') }}
                        <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-3 control-label" class="font-weight-normal">Name <span class="required">*</span></label>
                            <div class="col-md-6">
                                <input id="name" name="name" type="text" class="form-control" value="{{ old('name') ?: $store->name }}" required>
                            </div>
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group {{ $errors->has('rank') ? ' has-error' : '' }}">
                            <label for="rank" class="col-md-3 control-label" class="font-weight-normal">Rank</label>
                            <div class="col-md-6">
                                <input id="rank" name="rank" type="number" class="form-control" value="{{ old('rank') ?: $store->rank }}" required>
                            </div>
                            @if ($errors->has('rank'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('rank') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="divider"> </div>
                        <div class="row">
                            <div class="col-sm-9 col-sm-offset-3">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
    <!-- end: page -->
@endsection

resources/views/admin/stores/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Stores')

@section('content')
    <!-- start: page -->
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <section class="panel">
                <header class="panel-heading">
                    <h2 class="panel-title">Stores Listing</h2>
                    <div class="panel-actions">
                        <a href="{{ admin_route('stores.create') }}">
                            <button type="button" class="mb-xs mt-xs mr-xs btn btn-xs btn-primary pull-right"><i class="fa fa-plus"></i> New Store</button>
                        </a>
                    </div>
                </header>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-hover mb-none">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Categories</th>
                                <th>Rank</th>
                                <th>Created</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($stores as $key => $store)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $store->name }}</td>
                                    <td>{{ $store->categories->count() }}</td>
                                    <td>{{ $store->rank}}</td>
                                    <td>{{ $store->created_at}}</td>
                                    <td class="actions-hover actions-fade">
                                        <a href="{{ admin_route('stores.edit', $store->id) }}"><i class="fa fa-pencil"></i></a>
                                        <a href="" class="delete-row"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <!-- end: page -->
@endsection