routes/admin.php
<?php


/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| This file is where the admin routes should be placed
| and remember all routes defined here are prefixed with /admin automatically
|
*/


Route::get('/', 'DashboardController@index')->name('dashboard');

Route::resource('stores', 'StoreController');
Route::resource('categories', 'CategoryController');
Route::post('categories/upload', 'CategoryController@upload');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

// pages
Route::get('about', 'HomeController@about');
Route::get('faq', 'HomeController@faq');
Route::get('contact', 'HomeController@getContact');
Route::post('contact', 'HomeController@postContact');
Route::get('terms', 'HomeController@terms');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Category extends Model
{
    protected $guarded = ['id'];

    use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function store() {
        return $this->belongsTo(Store::class);
    }

    public function subcategories() {
        return $this->hasMany(Subcategory::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Storage;

use App\Category;
use App\File;

class CategoryController extends Controller
{
    protected $category;

    public function __construct(Category $category)
    {
        $this->category = $category;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->category->paginate(20);

        return admin_view('categories.index', [
            'categories' => $categories
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return admin_view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|min:5',
            'store_id' => 'required',
            'image' => 'required|single_image',
        ]);

        $category = $this->category->create([
            'name' => $request->name,
            'store_id' => $request->store_id,
            'image' => $request->image,
        ]);

        return back()->withSuccess('Category created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->category->findOrFail($id);
        $image = File::findOrFail($category->image);
        $pos = strrpos($image->link, '.');
        $ext = strtolower(substr($image->link, ++$pos));

        return admin_view('categories.edit', [
            'category' => $category,
            '_file' => json_encode([
                '_id' => $image->id,
                'name' => $image->name,
                'size' => $image->size,
                'type' => $image->type.'/'.$ext,
                'file' => image_path('categories/'.$image->link),
                'url' => image('categories/'.$image->link)
            ]),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = $this->category->findOrFail($id);

        $this->validate($request, [
            'name' => 'required|min:5',
            'store_id' => 'required',
        ]);

        $category->update([
            'name' => $request->name,
            'store_id' => $request->store_id,
        ]);

        return back()->withSuccess('Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = $this->category->findOrFail($id);
        if($category->admin){
            session()->flash('error', 'Failed! You need to remove category\'s admin right first');
        }
        else{
            $category->delete();
            session()->flash('success', 'Category deleted successfully');
        }
        return response('reload');
    }

    /**
     * Upload images via js plugin
     * @param Request $request
     * @return array
     */
    public function upload(Request $request) {
        $this->validate($request, [
            'image' => 'required'
        ]);

        $file = $request->file('image')[0];

        $validator = Validator::make(['image' => $file], ['image' => 'image|max:4300']);

        if($validator->fails()) {
            return abort(403, 'validation fails');
        }

        $path = '/uploads/images/categories';

        $name = str_random(20);

        $original_name = $file->getClientOriginalName();

        // Extract the extension
        $pos = strrpos($original_name, '.');
        $ext = substr($original_name, $pos);

        $full_name = $name.$ext;

        // save original
        Storage::put("{$path}/{$full_name}", file_get_contents($file->getRealPath()));

        // store file
        $file_ = File::create([
            'name' => $original_name,
            'link' => $full_name,
            'path' => $request->getUriForPath($path),
            'size' => $file->getClientSize(),
            'type' => 'image'
        ]);

        return ['file_id' => $file_->getAttribute('id')];
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')

@section('title', 'New Category')

@push('styles')
    <link href="/plugins/fileuploader/src/jquery.fileuploader.css" type="text/css" rel="stylesheet" />
    <link href="/plugins/fileuploader/src/jquery.fileuploader-theme-dragdrop.css" type="text/css" rel="stylesheet" />
@endpush

@section('content')
    <!-- start: page -->
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <section class="panel">
                <header class="panel-heading">
                    <h2 class="panel-title">New Category</h2>
                </header>
                <div class="panel-body">
                    <form class="form-horizontal form-bordered" role="form" method="POST" action="{{ admin_route('categories.store') }}">
                        {{ csrf_field() }}
                        <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-3 control-label" class="font-weight-normal">Name <span class="required">*</span></label>
                            <div class="col-md-6">
                                <input id="name" name="name" type="text" class="form-control" value="{{ old('name') }}" required>
                            </div>
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group {{ $errors->has('rank') ? ' has-error' : '' }}">
                            <label for="rank" class="col-md-3 control-label" class="font-weight-normal">Store</label>
                            <div class="col-md-6">
                                <select id="store_id" name="store_id" data-plugin-selectTwo class="form-control populate" placeholder="Select">
                                    <option value="">Select One</option>
                                    @foreach(\App\Store::ranked()->get() as $store)
                                        <option value="{{ $store->id }}" {{ old('name') == $store->name ? 'selected' : '' }}>{{ $store->name }}</option>
                                    @endforeach

                                </select>
                            </div>
                            @if ($errors->has('rank'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('rank') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group {{ $errors->has('image') ? ' has-error' : '' }}">
                            <div class="col-md-offset-2 col-md-8">
                                <input id="cat_image" name="image" type="file" class="form-control">
                                <input id="image" name="image" type="hidden" class="form-control" value="{{ old('image') }}" required>
                            </div>
                            @if ($errors->has('image'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('image') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="divider"> </div>
                        <div class="row">
                            <div class="col-sm-9 col-sm-offset-3">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
    <!-- end: page -->
@endsection

@push('scripts')
    <script src="/plugins/fileuploader/src/jquery.fileuploader.js"></script>
    @include('_partials/image_upload')
@endpush

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Edit Category')

@push('styles')
    <link href="/plugins/fileuploader/src/jquery.fileuploader.css" type="text/css" rel="stylesheet" />
    <link href="/plugins/fileuploader/src/jquery.fileuploader-theme-dragdrop.css" type="text/css" rel="stylesheet" />
@endpush

@section('content')
    <!-- start: page -->
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <section class="panel">
                <header class="panel-heading">
                    <h2 class="panel-title">{{ $category->name }}</h2>
                </header>
                <div class="panel-body">
                    <form class="form-horizontal form-bordered" role="form" method="POST" action="{{ admin_route('categories.update', $category->id) }}>
                        {{ csrf_field() }}
                        {{ method_field('put') }}
                        <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-3 control-label" class="font-weight-normal">Name <span class="required">*</span></label>
                            <div class="col-md-6">
                                <input id="name" name="name" type="text" class="form-control" value="{{ old('name') ?: $category->name }}" required>
                            </div>
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group {{ $errors->has('rank') ? ' has-error' : '' }}">
                            <label for="rank" class="col-md-3 control-label" class="font-weight-normal">Store</label>
                            <div class="col-md-6">
                                <select id="store_id" name="store_id" data-plugin-selectTwo class="form-control populate" placeholder="Select">
                                    <option value="">Select One</option>
                                    @foreach(\App\Store::ranked()->get() as $store)
                                        <option value="{{ $store->id }}" {{ (old('name') ?: $category->store->name) == $store->name ? 'selected' : '' }}>{{ $store->name }}</option>
                                    @endforeach

                                </select>
                            </div>
                            @if ($errors->has('rank'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('rank') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group {{ $errors->has('image') ? ' has-error' : '' }}">
                            <div class="col-md-offset-2 col-md-8">
                                <input id="cat_image" name="image" type="file" class="form-control" data-fileuploader-files="">
                                <input id="image" name="image" type="hidden" class="form-control" value="{{ old('image') }}" required>
                            </div>
                            @if ($errors->has('image'))
                                <span class="help-block">
                                            <strong>{{ $errors->first('image') }}</strong>
                                        </span>
                            @endif
                        </div>

                        <div class="divider"> </div>
                        <div class="row">
                            <div class="col-sm-9 col-sm-offset-3">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> Save</button>
                            </div>
                        </div>
                    </form>
            </section>
        </div>
    </div>
    <!-- end: page -->
@endsection

@push('scripts')
    <script src="/plugins/fileuploader/src/jquery.fileuploader.js"></script>
    @include('_partials/image_upload')
@endpush

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Categories')

@section('content')
    <!-- start: page -->
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <section class="panel">
                <header class="panel-heading">
                    <h2 class="panel-title">Categories Listing</h2>
                    <div class="panel-actions">
                        <a href="{{ admin_route('categories.create') }}">
                            <button type="button" class="mb-xs mt-xs mr-xs btn btn-xs btn-primary pull-right"><i class="fa fa-plus"></i> New Store</button>
                        </a>
                    </div>
                </header>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-hover mb-none">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Store</th>
                                <th>Subcategories</th>
                                <th>Created</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $key => $category)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $category->name }}</td>
                                    <td>{{ $category->store->name }}</td>
                                    <td>{{ $category->subcategories()->count() }}</td>
                                    <td>{{ $category->created_at}}</td>
                                    <td class="actions-hover actions-fade">
                                        <a href="{{ admin_route('categories.edit', $category->id) }}"><i class="fa fa-pencil"></i></a>
                                        <a href="" class="delete-row"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <!-- end: page -->
@endsection